# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    #DEBUG
    echo "Build Flavor:" $buildFlavor
    echo "Resource Group:" $resourceGroupName
    echo "Image:" $imageTag
    echo "Relative save location:" $relativeSaveLocation
    echo "DNS Url:" $dnsUrl

    echo "az login -u $HACKER_LOGIN -p $HACKER_PASSWORD"
    az login -u $HACKER_LOGIN -p $HACKER_PASSWORD
    # az group create --location westus2 --name $resourceGroupName
    # az acr create --name $registryName --resource-group $resourceGroupName --sku Basic

    #get the acr repository id to tag image with.
    ACR_ID=`az acr list -g $resourceGroupName --query "[].{acrLoginServer:loginServer}" --output json | jq .[].acrLoginServer | sed 's/\"//g'`

    echo "ACR ID: "$ACR_ID
    az acr update -n $registryName --admin-enabled true

    #Get the acr admin password and login to the registry
    acrPassword=$(az acr credential show -n $registryName -o json | jq -r '[.passwords[0].value] | .[]')

    docker login $ACR_ID -u $registryName -p $acrPassword
    echo "Authenticated to ACR with username and password"

    git clone https://github.com/samiyaakhtar/openhack-devops-team.git

    TAG=$ACR_ID"/devopsoh/"$imageTag

    TAG="$TAG-poi"
    echo "TAG: "$TAG
    cd ./openhack-devops-team/apis/poi/web
    docker build . -t $TAG
    docker push $TAG
    echo -e "\nSuccessfully pushed image: "$TAG
    cd $HOME
    ls
    pwd

    TAG="$TAG-trips"
    echo "TAG: "$TAG
    cd ./openhack-devops-team/apis/trips/
    docker build . -t $TAG
    docker push $TAG
    echo -e "\nSuccessfully pushed image: "$TAG
  displayName: 'Run a multi-line script'
  env:
    HACKER_LOGIN: $(HACKER_LOGIN)
    HACKER_PASSWORD: $(HACKER_PASSWORD)
    imageTag: "0.1"
    relativeSaveLocation: ""
    resourceGroupName: "saakhtaopenhackdevopsrg"
    registryName: "saakhtaopenhackacr"
