# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd ./apis/trips/tests/
    go get
    go test ./...
  displayName: "Trips unit test"

- script: |
    cd ./apis/user-java/
    mvn clean test
  displayName: "User-Java unit test"

- script: |
    cd ./apis/userprofile/
    npm install
    npm run test
  displayName: "Userprofile unit test"

- script: |
    #DEBUG
    echo "Build Flavor:" $buildFlavor
    echo "Resource Group:" $resourceGroupName
    echo "Image:" $imageTag
    echo "Relative save location:" $relativeSaveLocation
    echo "DNS Url:" $dnsUrl

    echo "az login -u $HACKER_LOGIN -p $HACKER_PASSWORD"
    az login -u $HACKER_LOGIN -p $HACKER_PASSWORD
    # az group create --location westus2 --name $resourceGroupName
    # az acr create --name $registryName --resource-group $resourceGroupName --sku Basic

    #get the acr repository id to tag image with.
    ACR_ID=`az acr list -g $resourceGroupName --query "[].{acrLoginServer:loginServer}" --output json | jq .[].acrLoginServer | sed 's/\"//g'`

    echo "ACR ID: "$ACR_ID
    az acr update -n $registryName --admin-enabled true

    #Get the acr admin password and login to the registry
    acrPassword=$(az acr credential show -n $registryName -o json | jq -r '[.passwords[0].value] | .[]')

    docker login $ACR_ID -u $registryName -p $acrPassword
    echo "Authenticated to ACR with username and password"

    wd=$(pwd)
    TAG=$ACR_ID"/devopsoh/"$imageTag

    cd ./apis/poi/web
    docker build . -t $TAG-poi
    docker push $TAG-poi
    echo -e "\nSuccessfully pushed image: "$TAG-poi
    cd $wd

    cd ./apis/trips/
    docker build . -t $TAG-trips
    docker push $TAG-trips
    echo -e "\nSuccessfully pushed image: "$TAG-trips
    cd $wd

    cd ./apis/user-java/
    docker build . -t $TAG-userjava
    docker push $TAG-userjava
    echo -e "\nSuccessfully pushed image: "$TAG-userjava
    cd $wd

    cd ./apis/userprofile/
    docker build . -t $TAG-userprofile
    docker push $TAG-userprofile
    echo -e "\nSuccessfully pushed image: "$TAG-userprofile
    cd $wd

    echo "Successfully pushed all 4 images for $imageTag"
  displayName: 'Push to container registry'
  env:
    HACKER_LOGIN: $(HACKER_LOGIN)
    HACKER_PASSWORD: $(HACKER_PASSWORD)
    imageTag: $(Build.BuildId)
    relativeSaveLocation: ""
    resourceGroupName: "saakhtaopenhackdevopsrg"
    registryName: "saakhtaopenhackacr"
